### ISSUE TITLE
Autocoins for Bybit?

### ISSUE THREAD

**Issue by Bulan** [LompeBoer/go-autocoins#3]
Hi!

looked through the code and saw that it was prepared for adding Bybit, is there a plan for when that will be released?

Unfortunately I haven't got any skills in Go yet, but are there other things one could help with?

**Comment by LompeBoer** [comment]
Yes, I was preparing to add ByBit to get the data. However their API is a bit more limiting in comparison with Binance.  
So it requires some substantial changes to make it work with ByBit, because there is some data not in their API.  
But using go-autocoins with Binance API is accurate enough to be used with the WH ByBit bot, at least in my experience.  
  
For now the ByBit API implementation is on hold. Currently I am working on using the Binance stream API for more up-to-date/realtime processing of the data.

**Comment by Bulan** [comment]
Thanx for swift reply, then I understand, I'll go ahead and try with Binance then for now!
